name: CI

on:
  pull_request_target:
    branches: [competition]
  push:
    branches: [competition]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
# ----------------------- DETECT CHANGES ----------------------- #
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      java-changed: ${{ steps.changes.outputs.java }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            java:
              - '**/*.java'
              - '**/*.gradle'

# ----------------------- JAVA ----------------------- #

  format-java:
        if: needs.detect-changes.outputs.java-changed == 'true'
        needs: [detect-changes]
        uses: ./.github/workflows/reusable-format-java.yml

  build-java:
    needs: [detect-changes, format-java]
    uses: ./.github/workflows/reusable-build-java.yml     
